In [5]:
import numpy as np

x = np.array([1,2,3])
y = x.tolist()

print(y)

[1, 2, 3]


In [19]:
import numpy as np

a = np.arange(9).reshape(3,3)
print("the array :") 
print(a)

sum_diagonal = np.trace(a)
print("the sum of the diagonal of this array is :", sum_diagonal)

the array :
[[0 1 2]
 [3 4 5]
 [6 7 8]]
the sum of the diagonal of this array is : 12


In [25]:
import numpy as np

b = np.array([(1,4),(7,3),(8,2),(14,5)])
print("the array :") 
print(b)

print("Values higher than 5 =", b[b>5])
print("Their indices are ", np.nonzero(b > 5))

the array :
[[ 1  4]
 [ 7  3]
 [ 8  2]
 [14  5]]
Values higher than 5 = [ 7  8 14]
Their indices are  (array([1, 2, 3], dtype=int64), array([0, 0, 0], dtype=int64))


In [38]:
import numpy as np

A = np.array([(4,2),(5,3),(4,7)])
B = np.array([(5,3),(1,9),(10,4)])

C = np.add(A,B)
print(C)

[[ 9  5]
 [ 6 12]
 [14 11]]


In [37]:
import numpy as np

array1 = np.array([(4,2,5),(5,3,9),(4,7,1)])
print("\n the array :\n")
print(array1)

array2 = array1 - array1.mean(axis=1, keepdims=True)
print("\n the new array after substracting the mean of each row :\n") 
print(array2)


 the array :

[[4 2 5]
 [5 3 9]
 [4 7 1]]

 the new array after substracting the mean of each row :

[[ 0.33333333 -1.66666667  1.33333333]
 [-0.66666667 -2.66666667  3.33333333]
 [ 0.          3.         -3.        ]]
